DROP TABLE t_user;
CREATE TABLE t_user(
	iuser INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	uid VARCHAR(20) NOT NULL UNIQUE,
	upw VARCHAR(100) NOT NULL,
	unm VARCHAR(5) NOT NULL,
	gender INT(1) UNSIGNED CHECK(gender IN (0, 1)),
	regdt DATETIME DEFAULT NOW()
);